version: '3.8'

services:
  angular_app:
    build: .
    container_name: angular_frontend
    ports:
      - "4200:80"
    networks:
      - app_network
    depends_on:
      - api
  
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: php_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vitrine-retail
      MYSQL_USER: root
      MYSQL_PASSWORD: 123#Mudar
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
