version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: php_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vitrine-retail
      MYSQL_USER: root
      MYSQL_PASSWORD: 123#Mudar
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
